default:
	pdflatex HH4b.tex
	pdflatex HH4b.tex	
	pdflatex HH4b.tex	


clean:
	rm -rf *~ *.log *.pdf *.aux *.toc *.dvi *.blg *.out
	rm -rf paperscripts/*.pdf paperscripts/*~  paperscripts/*.dat paperscripts/*.tex 
